### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by h4ck94** [spumer/source-query-proxy-kernel-module#7]
hi, i was trying to install the sqproxy but i have some errors. can i contact somebody for help me out?

**Comment by spumer** [comment]
We can discuss here. Please provide more information about your errors.

Will be usefull post your OS, Kernel version, python version

And please check your bcc version is new, like in this comment: https://github.com/sqproxy/sqproxy/issues/115#issuecomment-1090722691

**Comment by h4ck94** [comment]
I have write you also on discord.  I need help with the complette installation.

**Comment by h4ck94** [comment]
> We can discuss here. Please provide more information about your errors.
> 
> Will be usefull post your OS, Kernel version, python version
> 
> And please check your bcc version is new, like in this comment: [sqproxy/sqproxy#115 (comment)](https://github.com/sqproxy/sqproxy/issues/115#issuecomment-1090722691)

i am using ubuntu 20.04.


5.4.0-139-generic

python3 -c 'import bcc; print(bcc.__version__)'
0.12.0
